// Generated by Wrangler on Wed Jul 03 2024 17:04:07 GMT+0300 (Eastern European Summer Time)
// by running `wrangler types`

interface Env {
	GITHUB_CLIENT_ID: "Iv23lilrZsjZ3noDLHU0";
	db: D1Database;
}
