// Generated by Wrangler on Thu Jul 04 2024 00:17:19 GMT+0300 (Eastern European Summer Time)
// by running `wrangler types`

interface Env {
	AUTH_GITHUB_ID: "Iv23lilrZsjZ3noDLHU0";
	db: D1Database;
}
